Repository react-native-device-info/react-native-device-info, pull requests merged in 2019-03, with the labels that each got.

#514 is battery charing android
  android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
  deviceinfo.d.ts
  deviceinfo.js
  deviceinfo.js.flow
Labels: feedback-requested

#404 Enabled battery monitoring mode to get actual battery data
  README.md
  ios/RNDeviceInfo.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: ios, wip

#589 Example demonstrating usage
  .npmignore
  example/.buckconfig
  example/.flowconfig
  example/.gitattributes
  example/.gitignore
  example/.watchmanconfig
  example/App.js
  example/__tests__/App.js
  example/android/app/BUCK
  example/android/app/build.gradle
  example/android/app/build_defs.bzl
  example/android/app/proguard-rules.pro
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/java/com/example/MainActivity.java
  example/android/app/src/main/java/com/example/MainApplication.java
  example/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  example/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  example/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  example/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  example/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  example/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  example/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  example/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  example/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  example/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  example/android/app/src/main/res/values/strings.xml
  example/android/app/src/main/res/values/styles.xml
  example/android/build.gradle
  example/android/gradle.properties
  example/android/gradle/wrapper/gradle-wrapper.jar
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/android/gradlew
  example/android/gradlew.bat
  example/android/keystores/BUCK
  example/android/keystores/debug.keystore.properties
  example/android/settings.gradle
  example/app.json
  example/babel.config.js
  example/index.js
  example/ios/example-tvOS/Info.plist
  example/ios/example-tvOSTests/Info.plist
  example/ios/example.xcodeproj/project.pbxproj
  example/ios/example.xcodeproj/xcshareddata/xcschemes/example-tvOS.xcscheme
  example/ios/example.xcodeproj/xcshareddata/xcschemes/example.xcscheme
  example/ios/example/AppDelegate.h
  example/ios/example/AppDelegate.m
  example/ios/example/Base.lproj/LaunchScreen.xib
  example/ios/example/Images.xcassets/AppIcon.appiconset/Contents.json
  example/ios/example/Images.xcassets/Contents.json
  example/ios/example/Info.plist
  example/ios/example/main.m
  example/ios/exampleTests/Info.plist
  example/ios/exampleTests/exampleTests.m
  example/package-lock.json
  example/package.json
  refresh-example.sh
Labels: docs, enhancement

#382 Uses this.reactContext instead of getCurrentActivity to check permissions for phoneNumber getter
  CHANGELOG.md
  android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Labels: android, ready-for-review

#269 Ask phoneNumber permissions according to Android os version
  CHANGELOG.md
  README.md
  android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Labels: android

#406 Support 'dom' Platform.OS for react-native-dom
  README.md
  deviceinfo.js
Labels: enhancement, feedback-requested

#375 feat: Adds support for Jest snapshot testing
  CHANGELOG.md
  default/index.js
  deviceinfo.js
  web/index.js
Labels: feedback-requested
