Repository react-native-device-info/react-native-device-info, pull requests merged in 2019-05, with the labels that each got.

#474 feat: Add getCameraPresence function
  CHANGELOG.md
  README.md
  android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
  default/index.js
  deviceinfo.d.ts
  deviceinfo.js
  deviceinfo.js.flow
  example/App.js
  package.json
  windows/RNDeviceInfo/RNDeviceInfoModule.cs
Labels: enhancement, reviewed-needs-changes

#628 chore: Update and cleanup project
  .gitignore
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  example/package-lock.json
  refresh-example.sh
  windows/.gitignore
  yarn.lock
Labels: feedback-requested

#678 fix: adding conditions for tvOS location providers
  CHANGELOG.md
  example/ios/example/AppDelegate.m
  example/package.json
  example/yarn.lock
  ios/RNDeviceInfo/RNDeviceInfo.m
  refresh-example.sh
Labels: bug, has PR, ios, ready-for-review
