Repository react-native-device-info/react-native-device-info, pull requests merged in 2019-04, with the labels that each got.

#616 docs: add Podfile and README to example, refresh example
  example/README.md
  example/ios/Podfile
  example/ios/example.xcodeproj/project.pbxproj
  example/package-lock.json
  example/package.json
  refresh-example.sh
Labels: docs, ios

#618 Add the 3th generation iPad pro to the device name list
  CHANGELOG.md
  README.md
  ios/RNDeviceInfo/RNDeviceInfo.m
Labels: feedback-requested, ios

#617 Podfile update
  RNDeviceInfo.podspec
  package-lock.json
Labels: ios

#545 Fix getUserAgent for android API level <= 16
  CHANGELOG.md
  android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
Labels: feedback-requested

#408 Use RCTSharedApplication instead of [UIApplication sharedApplication]
  CHANGELOG.md
  README.md
  ios/RNDeviceInfo/RNDeviceInfo.h
  ios/RNDeviceInfo/RNDeviceInfo.m
Labels: feedback-requested, reviewed-needs-changes
